


A parent except statement will catch sub-classed exceptions.
test_sub_exception_class using StopSection
  Creating an instance of class StopSection with parent classes:
    StopSection
    TestException
    Exception
    BaseException
    object
Found a TestException exception:
	 StopSection('Boo')
	With Context:
		None



The first matching except statement is run, others are ignored.
Note: the "print_mro(cls)" method of "TestException" is not run.
test_sub_exception_class using StopIterSection
Found a StopIteration exception:
	 StopIterSection('Boo')
	With Context:
		None



The order of the sub-classes does not matter here,
but the "print_mro(cls)" method of "TestException" is run this time.
test_sub_exception_class using StopIterSection2
  Creating an instance of class StopIterSection2 with parent classes:
    StopIterSection2
    TestException
    StopIteration
    Exception
    BaseException
    object
Found a StopIteration exception:
	 StopIterSection2('Boo')
	With Context:
		None



StopSection raised in the generator is caught.
do_test_gen using StopSection
J = 0
J = 1
J = 2
J = 3
J = 4
  Creating an instance of class StopSection with parent classes:
    StopSection
    TestException
    Exception
    BaseException
    object
  Stopped with Exception "StopSection"
     Reported as: StopSection()
         Reported with context: None



StopIterSection raised in the generator is converted to a RuntimeError.
do_test_gen using StopIterSection
J = 0
J = 1
J = 2
J = 3
J = 4
  Stopped with Exception "RuntimeError"
     Reported as: RuntimeError('generator raised StopIteration')
         Reported with context: StopIterSection()



With Return instead of a StopSection subclass.
do_test_gen using return
J = 0
J = 1
J = 2
J = 3
J = 4
    Done with test_gen_r.



With Return instead of a StopIteration subclass.
do_test_gen using return
J = 0
J = 1
J = 2
J = 3
J = 4
    Done with test_gen_r.



With Return at both levels instead of a StopIteration subclass.
do_test_2nd_gen using return
do_test_gen using return
J = 0
J = 1
    Done with test_gen_r(2).
do_test_gen using return
J = 0
J = 1
J = 2
    Done with test_gen_r(3).
do_test_gen using return
J = 0
J = 1
J = 2
J = 3
    Done with test_gen_r(4).
    Done with test_2nd_gen_r.



With Return at inner level instead of a StopIteration subclass.
do_test_2nd_gen using StopIterSection2
do_test_gen using return
J = 0
J = 1
    Done with test_gen_r(2).
do_test_gen using return
J = 0
J = 1
J = 2
    Done with test_gen_r(3).
do_test_gen using return
J = 0
J = 1
J = 2
J = 3
    Done with test_gen_r(4).
  Creating an instance of class StopIterSection2 with parent classes:
    StopIterSection2
    TestException
    StopIteration
    Exception
    BaseException
    object
  Stopped with Exception "RuntimeError"
     Reported as: RuntimeError('generator raised StopIteration')
         Reported with context: StopIterSection2()



With Return at inner level instead of a StopIteration subclass.
do_test_2nd_gen using StopSection
do_test_gen using return
J = 0
J = 1
    Done with test_gen_r(2).
do_test_gen using return
J = 0
J = 1
J = 2
    Done with test_gen_r(3).
do_test_gen using return
J = 0
J = 1
J = 2
J = 3
    Done with test_gen_r(4).
  Creating an instance of class StopSection with parent classes:
    StopSection
    TestException
    Exception
    BaseException
    object
  Stopped with Exception "StopSection"
     Reported as: StopSection()
         Reported with context: None



With Return at outer level instead of a StopIteration subclass.
do_test_2nd_gen using return
do_test_gen using StopSection
J = 0
J = 1
  Creating an instance of class StopSection with parent classes:
    StopSection
    TestException
    Exception
    BaseException
    object
  Stopped with Exception "StopSection"
     Reported as: StopSection()
         Reported with context: None



With Return at outer level instead of a StopIteration subclass.
do_test_2nd_gen using return
do_test_gen using StopIterSection2
J = 0
J = 1
  Creating an instance of class StopIterSection2 with parent classes:
    StopIterSection2
    TestException
    StopIteration
    Exception
    BaseException
    object
  Stopped with Exception "RuntimeError"
     Reported as: RuntimeError('generator raised StopIteration')
         Reported with context: StopIterSection2()



With StopSection at both levels.
do_test_2nd_gen using StopSection
do_test_gen using StopSection
J = 0
J = 1
  Creating an instance of class StopSection with parent classes:
    StopSection
    TestException
    Exception
    BaseException
    object
  Stopped with Exception "StopSection"
     Reported as: StopSection()
         Reported with context: None



With StopIterSection2 at both levels.
do_test_2nd_gen using StopIterSection2
do_test_gen using StopIterSection2
J = 0
J = 1
  Creating an instance of class StopIterSection2 with parent classes:
    StopIterSection2
    TestException
    StopIteration
    The thread 'MainThread' (0x1) has exited with code 0 (0x0).
Exception
    BaseException
    object
  Stopped with Exception "RuntimeError"
     Reported as: RuntimeError('generator raised StopIteration')
         Reported with context: StopIterSection2()
With StopIteration at both levels.
do_test_2nd_gen using StopIteration
do_test_gen using StopIteration
J = 0
J = 1
  Stopped with Exception "RuntimeError"
     Reported as: RuntimeError('generator raised StopIteration')
         Reported with context: StopIteration()



Really Done
The program 'python.exe' has exited with code 0 (0x0).
